version: '3'

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.1.0
    volumes:
      - elk-data:/usr/share/elasticsearch/data
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk

  logstash:
    image: docker.elastic.co/logstash/logstash-oss:6.1.0
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    ports:
      - "5000:5000"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    depends_on:
      - elasticsearch


  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.1.0
    volumes:
      - ./kibana/config/:/usr/share/kibana/config:ro
    networks:
      - elk
    depends_on:
      - elasticsearch

  nginx-proxy:
    image: nginx-proxy:1.0
    volumes:
      - ./nginx-proxy/nginx/conf.d/proxy.conf:/etc/nginx/conf.d/proxy.conf:ro
      - ./nginx-proxy/nginx/htpasswd:/etc/nginx/htpasswd:ro
    ports:
      - "443:443"
    networks:
      - elk
    depends_on:
      - kibana

networks:
  elk:
    external:
      name: elk

volumes:
  elk-data:
